BEGIN
	ALTER INDEX [UX_Group_ObjectGUID]
		ON [ActiveDirectory].[Group]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_Group_DistinguishedName]
		ON [ActiveDirectory].[Group]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [IX_Group_ParentOrganizationalUnitId]
		ON [ActiveDirectory].[Group]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [IX_Group_ObjectCategoryId]
		ON [ActiveDirectory].[Group]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [IX_Group_GroupTypeId]
		ON [ActiveDirectory].[Group]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_GroupManagerGroup_Key]
		ON [ActiveDirectory].[GroupManagerGroup]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_GroupManagerUser_Key]
		ON [ActiveDirectory].[GroupManagerUser]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_GroupMembershipGroup_Key]
		ON [ActiveDirectory].[GroupMembershipGroup]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_GroupMembershipUser_Key]
		ON [ActiveDirectory].[GroupMembershipUser]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_GroupObjectClass_Key]
		ON [ActiveDirectory].[GroupObjectClass]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_ManagerialHierarchy_Key]
		ON [ActiveDirectory].[ManagerialHierarchy]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_ObjectCategory_Name]
		ON [ActiveDirectory].[ObjectCategory]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_ObjectClass_Name]
		ON [ActiveDirectory].[ObjectClass]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_OrganizationalUnit_LDIFPath]
		ON [ActiveDirectory].[OrganizationalUnit]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_PhoneType_Name]
		ON [ActiveDirectory].[PhoneType]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_User_ObjectGUID]
		ON [ActiveDirectory].[User]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_User_DistinguishedName]
		ON [ActiveDirectory].[User]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [IX_User_ParentOrganizationalUnitId]
		ON [ActiveDirectory].[User]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [IX_User_ObjectCategoryId]
		ON [ActiveDirectory].[User]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [IX_User_UserAccountControlId]
		ON [ActiveDirectory].[User]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_UserAccountControlFlag_Name]
		ON [ActiveDirectory].[UserAccountControlFlag]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [UX_UserObjectClass_Key]
		ON [ActiveDirectory].[UserObjectClass]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [IX_UserPhone_UserId]
		ON [ActiveDirectory].[UserPhone]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

	ALTER INDEX [IX_UserPhone_PhoneTypeId]
		ON [ActiveDirectory].[UserPhone]
		REBUILD PARTITION = ALL
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
END
