CREATE DATABASE [$(PrimaryFilePath)]
	CONTAINMENT = NONE
	ON
		PRIMARY
		(
			NAME = N'$(PrimaryFileName)',
			FILENAME = N'$(PrimaryFilePath)',
			SIZE = 182272KB,
			MAXSIZE = UNLIMITED,
			FILEGROWTH = 65536KB
		)
		LOG ON
		(
			NAME = N'$(LogFileName)',
			FILENAME = N'$(LogFilePath)',
			SIZE = 8192KB,
			MAXSIZE = 2048GB,
			FILEGROWTH = 65536KB
		)
		WITH
			CATALOG_COLLATION = DATABASE_DEFAULT,
			LEDGER = OFF
ALTER DATABASE [$(PrimaryFilePath)]
	SET ANSI_NULL_DEFAULT OFF
ALTER DATABASE [$(PrimaryFilePath)]
	SET ANSI_NULLS OFF
ALTER DATABASE [$(PrimaryFilePath)]
	SET ANSI_PADDING OFF
ALTER DATABASE [$(PrimaryFilePath)] SET ANSI_WARNINGS OFF
ALTER DATABASE [$(PrimaryFilePath)] SET ARITHABORT OFF
ALTER DATABASE [$(PrimaryFilePath)] SET AUTO_CLOSE ON
ALTER DATABASE [$(PrimaryFilePath)] SET AUTO_SHRINK ON
ALTER DATABASE [$(PrimaryFilePath)] SET AUTO_UPDATE_STATISTICS ON
ALTER DATABASE [$(PrimaryFilePath)] SET CURSOR_CLOSE_ON_COMMIT OFF
ALTER DATABASE [$(PrimaryFilePath)] SET CURSOR_DEFAULT GLOBAL
ALTER DATABASE [$(PrimaryFilePath)] SET CONCAT_NULL_YIELDS_NULL OFF
ALTER DATABASE [$(PrimaryFilePath)] SET NUMERIC_ROUNDABORT OFF
ALTER DATABASE [$(PrimaryFilePath)] SET QUOTED_IDENTIFIER OFF
ALTER DATABASE [$(PrimaryFilePath)] SET RECURSIVE_TRIGGERS OFF
ALTER DATABASE [$(PrimaryFilePath)] SET ENABLE_BROKER
ALTER DATABASE [$(PrimaryFilePath)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
ALTER DATABASE [$(PrimaryFilePath)] SET DATE_CORRELATION_OPTIMIZATION OFF
ALTER DATABASE [$(PrimaryFilePath)] SET TRUSTWORTHY OFF
ALTER DATABASE [$(PrimaryFilePath)] SET ALLOW_SNAPSHOT_ISOLATION OFF
ALTER DATABASE [$(PrimaryFilePath)] SET PARAMETERIZATION SIMPLE
ALTER DATABASE [$(PrimaryFilePath)] SET READ_COMMITTED_SNAPSHOT OFF
ALTER DATABASE [$(PrimaryFilePath)] SET HONOR_BROKER_PRIORITY OFF
ALTER DATABASE [$(PrimaryFilePath)] SET RECOVERY SIMPLE
ALTER DATABASE [$(PrimaryFilePath)] SET  MULTI_USER
ALTER DATABASE [$(PrimaryFilePath)] SET PAGE_VERIFY CHECKSUM
ALTER DATABASE [$(PrimaryFilePath)] SET DB_CHAINING OFF
ALTER DATABASE [$(PrimaryFilePath)] SET FILESTREAM (NON_TRANSACTED_ACCESS = OFF)
ALTER DATABASE [$(PrimaryFilePath)] SET TARGET_RECOVERY_TIME = 60 SECONDS
ALTER DATABASE [$(PrimaryFilePath)] SET DELAYED_DURABILITY = DISABLED
ALTER DATABASE [$(PrimaryFilePath)] SET ACCELERATED_DATABASE_RECOVERY = OFF
ALTER DATABASE [$(PrimaryFilePath)] SET QUERY_STORE = ON
ALTER DATABASE [$(PrimaryFilePath)] SET QUERY_STORE
	(
		OPERATION_MODE = READ_WRITE,
		CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),
		DATA_FLUSH_INTERVAL_SECONDS = 900,
		INTERVAL_LENGTH_MINUTES = 60,
		MAX_STORAGE_SIZE_MB = 1000,
		QUERY_CAPTURE_MODE = AUTO,
		SIZE_BASED_CLEANUP_MODE = AUTO,
		MAX_PLANS_PER_QUERY = 200,
		WAIT_STATS_CAPTURE_MODE = ON
	)
ALTER DATABASE [$(PrimaryFilePath)] SET READ_WRITE
