DECLARE @TypeCrossMatch TABLE
(
	[SQLServerType] [sys].[sysname] NOT NULL,
	[SqlType] [sys].[sysname] NULL,
	[CLRType] [sys].[sysname] NULL
)
INSERT INTO @TypeCrossMatch([SQLServerType], [SqlType], [CLRType]) VALUES
	(N'bigint', N'System.Data.SqlTypes.SqlInt64', N'System.Int64'),
	(N'binary', N'System.Data.SqlTypes.SqlBytes', N'System.Byte[]'),
	(N'bit', N'System.Data.SqlTypes.SqlBoolean', N'System.Boolean'),
	(N'char', N'System.Data.SqlTypes.SqlChars', N'System.Char[]'),
	(N'cursor', NULL, NULL),
	(N'date', N'System.Data.SqlTypes.SqlDateTime', N'System.DateTime'),
	(N'datetime', N'System.Data.SqlTypes.SqlDateTime', N'System.DateTime'),
	(N'datetime2', N'System.Data.SqlTypes.SqlDateTime', N'System.DateTime'),
	(N'datetimeoffset', NULL, N'System.DateTimeOffset'),
	(N'decimal', N'System.Data.SqlTypes.SqlDecimal', N'System.Decimal'),
	(N'float', N'System.Data.SqlTypes.SqlDouble', N'System.Double'),
	(N'geography', N'System.Data.SqlTypes.SqlGeography', NULL),
	(N'geometry', N'System.Data.SqlTypes.SqlGeometry', NULL),
	(N'hierarchyid', N'System.Data.SqlTypes.SqlHierarchyId', NULL),
	(N'image', N'System.Data.SqlTypes.SqlBinary', N'System.Byte[]'),
	(N'int', N'System.Data.SqlTypes.SqlInt32', N'System.Int32'),
	(N'money', N'System.Data.SqlTypes.SqlMoney', N'System.Decimal'),
	(N'nchar', N'System.Data.SqlTypes.SqlChars', N'System.Char[]'),
	(N'ntext', N'System.Data.SqlTypes.SqlString', N'System.String'),
	(N'numeric', N'System.Data.SqlTypes.SqlDecimal', N'System.Decimal'),
	(N'nvarchar', N'System.Data.SqlTypes.SqlString', N'System.String'),
	(N'real', N'System.Data.SqlTypes.SqlSingle', N'System.Single'),
	(N'rowversion', NULL, N'System.Byte[]'),
	(N'smallint', N'System.Data.SqlTypes.SqlInt16', N'System.Int16'),
	(N'smallmoney', N'System.Data.SqlTypes.SqlMoney', N'System.Decimal'),
	(N'sql_variant', NULL, N'System.Object'),
	(N'table', NULL, NULL),
	(N'text', N'System.Data.SqlTypes.SqlString', N'System.String'),
	(N'time', NULL, N'System.TimeSpan'),
	(N'timestamp', N'System.Data.SqlTypes.SqlBinary', N'System.Byte[]'),
	(N'tinyint', N'System.Data.SqlTypes.SqlByte', N'System.Byte'),
	(N'uniqueidentifier', N'System.Data.SqlTypes.SqlGuid', N'System.Guid'),
	(N'varbinary', N'System.Data.SqlTypes.SqlBytes, SqlBinary', N'System.Byte[]'),
	(N'varchar', N'System.Data.SqlTypes.SqlString', N'System.String'),
	(N'xml', N'System.Data.SqlTypes.SqlXml', NULL)
